kind: Service
apiVersion: v1
metadata:
  name: spring-boot-ci-demo-server
spec:
  selector:
    app: spring-boot-ci-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-ci-demo
  labels:
    app: spring-boot-ci-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-ci-demo
  template:
    metadata:
      labels:
        app: spring-boot-ci-demo
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      -name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
